baseURL = "https://alanderos91.github.io/"
languageCode = 'en-us'
title = 'Alfonso Landeros'
theme = "hugo-astatine-theme"

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Turn off tags and categories
[taxonomies]

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
[[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = -180
    
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = -120

[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = -90

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = "The homepage of Alfonso Landeros"
    # Author of the site
    authorName = "Alfonso Landeros"
    # Main image for the author. This will be the default image for SEO.
    # [params.imgname]
        # name = "img/main.jpg"
        # Add an alt description for the image
        # alt = "Profile picture"

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    # blogrss = false


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
